language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.2
  - 2.2.10
#  - 2.3.8
gemfile:
  - gemfiles/rails32_paperclip2x.gemfile
  - gemfiles/rails32_paperclip3x.gemfile
  - gemfiles/rails32_paperclip4x.gemfile
  - gemfiles/rails40_paperclip42.gemfile
  - gemfiles/rails41_paperclip42.gemfile
  - gemfiles/rails42_paperclip42.gemfile
